trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release
  project: backend/MarketWatchApi.csproj

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '9.x'

- script: dotnet restore $(project)
  displayName: Restore

- script: dotnet build $(project) --configuration $(buildConfiguration) --no-restore
  displayName: Build

- script: dotnet test backend/MarketWatchApi.sln --configuration $(buildConfiguration) --no-build
  displayName: Test
  continueOnError: true

- script: dotnet publish $(project) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish

- task: AzureWebApp@1
  inputs:
    azureSubscription: sc-market-watch
    appType: webAppLinux
    appName: api-market-watch
    package: $(Build.ArtifactStagingDirectory)