trigger:
- azure-pipelines

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release

steps:

- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '9.0.x'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/MarketWatchApi.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: 'sc-market-watch'
    appType: webAppLinux
    appName: 'api-market-watch'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
